package com.punchcyber.patternicity.common.datatype.hbss.record

import java.time.Instant

import com.punchcyber.patternicity.common.datatype.json.record.{JsonHelperRecord, JsonRecord, JsonRecordRaw}
import org.apache.hadoop.hbase.client.Put

case class HbssThreatEventRecordRaw(`EPOComputerProperties.OSPlatform`: Option[String],
                                    `EPOEvents.ThreatName`: Option[String],
                                    `EPOComputerProperties.UserProperty4`: Option[String],
                                    `EPOEvents.AnalyzerHostName`: Option[String],
                                    `EPOEvents.AgentGUID`: Option[String],
                                    `EPOComputerProperties.IPHostName`: Option[String],
                                    `EPOComputerProperties.IPV6`: Option[String],
                                    `EPOComputerProperties.IPSubnet`: Option[String],
                                    `EPOComputerProperties.NumOfCPU`: Option[Int],
                                    `EPOEvents.AnalyzerName`: Option[String],
                                    `EPOComputerProperties.SubnetMask`: Option[String],
                                    `EPOComputerProperties.TimeZone`: Option[String],
                                    `EPOEvents.SourceMAC`: Option[String],
                                    `EPOEvents.TargetHostName`: Option[String],
                                    `EPOEvents.ThreatSeverity`: Option[Int],
                                    `EPOEvents.SourceUserName`: Option[String],
                                    `EPOComputerProperties.UserProperty2`: Option[String],
                                    `EPOComputerProperties.ParentID`: Option[Long],
                                    `EPOEvents.TargetPort`: Option[Int],
                                    `EPOComputerProperties.FreeMemory`: Option[Long],
                                    `EPOEvents.SourceURL`: Option[String],
                                    `EPOEvents.SourceIPV4`: Option[String],
                                    `EPOBranchNode.AutoID`: Option[Long],
                                    `EPOComputerProperties.DefaultLangID`: Option[String],
                                    `EPOComputerProperties.TotalPhysicalMemory`: Option[Long],
                                    `EPOEvents.TargetProcessName`: Option[String],
                                    `EPOComputerProperties.OSOEMID`: Option[String],
                                    `EPOComputerProperties.IPAddress`: Option[String],
                                    `EPOEvents.Analyzer`: Option[String],
                                    `EPOComputerProperties.IPXAddress`: Option[String],
                                    `EPOComputerProperties.OSBuildNum`: Option[Long],
                                    `EPOComputerProperties.Vdi`: String,
                                    `EPOComputerProperties.OSServicePackVer`: Option[String],
                                    `EPOBranchNode.NodeTextPath`: Option[String],
                                    `EPOComputerProperties.CPUSerialNum`: Option[String],
                                    `EPOLeafNode.LastUpdate`: String,
                                    `EPOComputerProperties.OSVersion`: Option[String],
                                    `EPOComputerProperties.IPSubnetMask`: Option[String],
                                    `EPOComputerProperties.OSType`: Option[String],
                                    `EPOEvents.TargetIPV6`: Option[String],
                                    `EPOComputerProperties.SystemDescription`: Option[String],
                                    `EPOEvents.ReceivedUTC`: String,
                                    `VSECustomEvent.MD5`: Option[String],
                                    `EPOEvents.TargetFileName`: Option[String],
                                    `EPOEvents.AnalyzerVersion`: Option[String],
                                    `EPOLeafNode.ManagedState`: Option[Long],
                                    `EPOLeafNode.NodeName`: Option[String],
                                    `EPOComputerProperties.Description`: Option[String],
                                    `EPOEvents.TargetMAC`: Option[String],
                                    `EPOEvents.ThreatCategory`: Option[String],
                                    `EPOEvents.TargetUserName`: Option[String],
                                    `EPOEvents.SourceHostName`: Option[String],
                                    `EPOEvents.TargetIPV4`: Option[String],
                                    `EPOEvents.AnalyzerIPV4`: Option[String],
                                    `EPOEvents.AnalyzerIPV6`: Option[String],
                                    `EPOComputerProperties.SysvolTotalSpace`: Option[Long],
                                    `EPOEvents.AnalyzerDetectionMethod`: Option[String],
                                    `EPOLeafNode.AgentGUID`: Option[String],
                                    `EPOEvents.ServerID`: Option[String],
                                    `EPOEvents.AnalyzerMAC`: Option[String],
                                    `EPOComputerProperties.OSBitMode`: Option[Int],
                                    `EPOLeafNode.AgentVersion`: Option[String],
                                    `EPOComputerProperties.UserProperty1`: Option[String],
                                    `EPOComputerProperties.UserProperty3`: Option[String],
                                    `EPOComputerProperties.IsPortable`: Boolean,
                                    `EPOComputerProperties.FreeDiskSpace`: Option[Long],
                                    `EPOEvents.SourceIPV6`: Option[String],
                                    `EPOEvents.SourceProcessName`: Option[String],
                                    `EPOLeafNode.Tags`: Option[String],
                                    `EPOEvents.ThreatActionTaken`: Option[String],
                                    `EPOComputerProperties.CPUSpeed`: Option[Long],
                                    `EPOComputerProperties.ComputerName`: Option[String],
                                    `EPOEvents.ThreatHandled`: Boolean,
                                    `EPOComputerProperties.NetAddress`: Option[String],
                                    `EPOEvents.ThreatType`: Option[String],
                                    `EPOEvents.TargetProtocol`: Option[String],
                                    `EPOComputerProperties.IPV4x`: Option[String],
                                    `EPOComputerProperties.SysvolFreeSpace`: Option[Long],
                                    `EPOEvents.AnalyzerEngineVersion`: Option[String],
                                    `EPOComputerProperties.DomainName`: Option[String],
                                    `EPOComputerProperties.UserName`: Option[String],
                                    `EPOComputerProperties.CPUType`: Option[String],
                                    `EPOComputerProperties.TotalDiskSpace`: Option[Long],
                                    `EPOEvents.ThreatEventID`: Option[Long],
                                    `EPOEvents.AnalyzerDATVersion`: Option[String],
                                    `EPOComputerProperties.SubnetAddress`: Option[String],
                                    `EPOLeafNode.ExcludedTags`: Option[String],
                                    `EPOEvents.DetectedUTC`: String,
                                    `EPOComputerProperties.LastAgentHandler`: Option[Long]) extends JsonRecordRaw

case class HbssThreatEventRecord(   EPOComputerProperties_OSPlatform: Option[String],
                                    EPOEvents_ThreatName: Option[String],
                                    EPOComputerProperties_UserProperty4: Option[String],
                                    EPOEvents_AnalyzerHostName: Option[String],
                                    EPOEvents_AgentGUID: Option[String],
                                    EPOComputerProperties_IPHostName: Option[String],
                                    EPOComputerProperties_IPV6: Option[String],
                                    EPOComputerProperties_IPSubnet: Option[String],
                                    EPOComputerProperties_NumOfCPU: Option[Int],
                                    EPOEvents_AnalyzerName: Option[String],
                                    EPOComputerProperties_SubnetMask: Option[String],
                                    EPOComputerProperties_TimeZone: Option[String],
                                    EPOEvents_SourceMAC: Option[String],
                                    EPOEvents_TargetHostName: Option[String],
                                    EPOEvents_ThreatSeverity: Option[Int],
                                    EPOEvents_SourceUserName: Option[String],
                                    EPOComputerProperties_UserProperty2: Option[String],
                                    EPOComputerProperties_ParentID: Option[Long],
                                    EPOEvents_TargetPort: Option[Int],
                                    EPOComputerProperties_FreeMemory: Option[Long],
                                    EPOEvents_SourceURL: Option[String],
                                    EPOEvents_SourceIPV4: Option[String],
                                    EPOBranchNode_AutoID: Option[Long],
                                    EPOComputerProperties_DefaultLangID: Option[String],
                                    EPOComputerProperties_TotalPhysicalMemory: Option[Long],
                                    EPOEvents_TargetProcessName: Option[String],
                                    EPOComputerProperties_OSOEMID: Option[String],
                                    EPOComputerProperties_IPAddress: Option[String],
                                    EPOEvents_Analyzer: Option[String],
                                    EPOComputerProperties_IPXAddress: Option[String],
                                    EPOComputerProperties_OSBuildNum: Option[Long],
                                    EPOComputerProperties_Vdi: String,
                                    EPOComputerProperties_OSServicePackVer: Option[String],
                                    EPOBranchNode_NodeTextPath: Option[String],
                                    EPOComputerProperties_CPUSerialNum: Option[String],
                                    EPOLeafNode_LastUpdate: Instant,
                                    EPOComputerProperties_OSVersion: Option[String],
                                    EPOComputerProperties_IPSubnetMask: Option[String],
                                    EPOComputerProperties_OSType: Option[String],
                                    EPOEvents_TargetIPV6: Option[String],
                                    EPOComputerProperties_SystemDescription: Option[String],
                                    EPOEvents_ReceivedUTC: Instant,
                                    VSECustomEvent_MD5: Option[String],
                                    EPOEvents_TargetFileName: Option[String],
                                    EPOEvents_AnalyzerVersion: Option[String],
                                    EPOLeafNode_ManagedState: Option[Long],
                                    EPOLeafNode_NodeName: Option[String],
                                    EPOComputerProperties_Description: Option[String],
                                    EPOEvents_TargetMAC: Option[String],
                                    EPOEvents_ThreatCategory: Option[String],
                                    EPOEvents_TargetUserName: Option[String],
                                    EPOEvents_SourceHostName: Option[String],
                                    EPOEvents_TargetIPV4: Option[String],
                                    EPOEvents_AnalyzerIPV4: Option[String],
                                    EPOEvents_AnalyzerIPV6: Option[String],
                                    EPOComputerProperties_SysvolTotalSpace: Option[Long],
                                    EPOEvents_AnalyzerDetectionMethod: Option[String],
                                    EPOLeafNode_AgentGUID: Option[String],
                                    EPOEvents_ServerID: Option[String],
                                    EPOEvents_AnalyzerMAC: Option[String],
                                    EPOComputerProperties_OSBitMode: Option[Int],
                                    EPOLeafNode_AgentVersion: Option[String],
                                    EPOComputerProperties_UserProperty1: Option[String],
                                    EPOComputerProperties_UserProperty3: Option[String],
                                    EPOComputerProperties_IsPortable: Boolean,
                                    EPOComputerProperties_FreeDiskSpace: Option[Long],
                                    EPOEvents_SourceIPV6: Option[String],
                                    EPOEvents_SourceProcessName: Option[String],
                                    EPOLeafNode_Tags: Option[String],
                                    EPOEvents_ThreatActionTaken: Option[String],
                                    EPOComputerProperties_CPUSpeed: Option[Long],
                                    EPOComputerProperties_ComputerName: Option[String],
                                    EPOEvents_ThreatHandled: Boolean,
                                    EPOComputerProperties_NetAddress: Option[String],
                                    EPOEvents_ThreatType: Option[String],
                                    EPOEvents_TargetProtocol: Option[String],
                                    EPOComputerProperties_IPV4x: Option[String],
                                    EPOComputerProperties_SysvolFreeSpace: Option[Long],
                                    EPOEvents_AnalyzerEngineVersion: Option[String],
                                    EPOComputerProperties_DomainName: Option[String],
                                    EPOComputerProperties_UserName: Option[String],
                                    EPOComputerProperties_CPUType: Option[String],
                                    EPOComputerProperties_TotalDiskSpace: Option[Long],
                                    EPOEvents_ThreatEventID: Option[Long],
                                    EPOEvents_AnalyzerDATVersion: Option[String],
                                    EPOComputerProperties_SubnetAddress: Option[String],
                                    EPOLeafNode_ExcludedTags: Option[String],
                                    EPOEvents_DetectedUTC: Instant,
                                    EPOComputerProperties_LastAgentHandler: Option[Long]) extends JsonRecord {
  override def getHbasePut: Put = {
    throw new UnsupportedOperationException("not yet implemented")
  }}


object HbssThreatEventRecord extends JsonHelperRecord {
  def apply(raw: HbssThreatEventRecordRaw): HbssThreatEventRecord = {
    HbssThreatEventRecord(
      EPOComputerProperties_OSPlatform = raw.`EPOComputerProperties.OSPlatform`,
      EPOEvents_ThreatName = raw.`EPOEvents.ThreatName`,
      EPOComputerProperties_UserProperty4 = raw.`EPOComputerProperties.UserProperty4`,
      EPOEvents_AnalyzerHostName = raw.`EPOEvents.AnalyzerHostName`,
      EPOEvents_AgentGUID = raw.`EPOEvents.AgentGUID`,
      EPOComputerProperties_IPHostName = raw.`EPOComputerProperties.IPHostName`,
      EPOComputerProperties_IPV6 = raw.`EPOComputerProperties.IPV6`,
      EPOComputerProperties_IPSubnet = raw.`EPOComputerProperties.IPSubnet`,
      EPOComputerProperties_NumOfCPU = raw.`EPOComputerProperties.NumOfCPU`,
      EPOEvents_AnalyzerName = raw.`EPOEvents.AnalyzerName`,
      EPOComputerProperties_SubnetMask = raw.`EPOComputerProperties.SubnetMask`,
      EPOComputerProperties_TimeZone = raw.`EPOComputerProperties.TimeZone`,
      EPOEvents_SourceMAC = raw.`EPOEvents.SourceMAC`,
      EPOEvents_TargetHostName = raw.`EPOEvents.TargetHostName`,
      EPOEvents_ThreatSeverity = raw.`EPOEvents.ThreatSeverity`,
      EPOEvents_SourceUserName = raw.`EPOEvents.SourceUserName`,
      EPOComputerProperties_UserProperty2 = raw.`EPOComputerProperties.UserProperty2`,
      EPOComputerProperties_ParentID = raw.`EPOComputerProperties.ParentID`,
      EPOEvents_TargetPort = raw.`EPOEvents.TargetPort`,
      EPOComputerProperties_FreeMemory = raw.`EPOComputerProperties.FreeMemory`,
      EPOEvents_SourceURL = raw.`EPOEvents.SourceURL`,
      EPOEvents_SourceIPV4 = raw.`EPOEvents.SourceIPV4`,
      EPOBranchNode_AutoID = raw.`EPOBranchNode.AutoID`,
      EPOComputerProperties_DefaultLangID = raw.`EPOComputerProperties.DefaultLangID`,
      EPOComputerProperties_TotalPhysicalMemory = raw.`EPOComputerProperties.TotalPhysicalMemory`,
      EPOEvents_TargetProcessName = raw.`EPOEvents.TargetProcessName`,
      EPOComputerProperties_OSOEMID = raw.`EPOComputerProperties.OSOEMID`,
      EPOComputerProperties_IPAddress = raw.`EPOComputerProperties.IPAddress`,
      EPOEvents_Analyzer = raw.`EPOEvents.Analyzer`,
      EPOComputerProperties_IPXAddress = raw.`EPOComputerProperties.IPXAddress`,
      EPOComputerProperties_OSBuildNum = raw.`EPOComputerProperties.OSBuildNum`,
      EPOComputerProperties_Vdi = raw.`EPOComputerProperties.Vdi`,
      EPOComputerProperties_OSServicePackVer = raw.`EPOComputerProperties.OSServicePackVer`,
      EPOBranchNode_NodeTextPath = raw.`EPOBranchNode.NodeTextPath`,
      EPOComputerProperties_CPUSerialNum = raw.`EPOComputerProperties.CPUSerialNum`,
      EPOLeafNode_LastUpdate = stringToInstant(raw.`EPOLeafNode.LastUpdate`),
      EPOComputerProperties_OSVersion = raw.`EPOComputerProperties.OSVersion`,
      EPOComputerProperties_IPSubnetMask = raw.`EPOComputerProperties.IPSubnetMask`,
      EPOComputerProperties_OSType = raw.`EPOComputerProperties.OSType`,
      EPOEvents_TargetIPV6 = raw.`EPOEvents.TargetIPV6`,
      EPOComputerProperties_SystemDescription = raw.`EPOComputerProperties.SystemDescription`,
      EPOEvents_ReceivedUTC = stringToInstant(raw.`EPOEvents.ReceivedUTC`),
      VSECustomEvent_MD5 = raw.`VSECustomEvent.MD5`,
      EPOEvents_TargetFileName = raw.`EPOEvents.TargetFileName`,
      EPOEvents_AnalyzerVersion = raw.`EPOEvents.AnalyzerVersion`,
      EPOLeafNode_ManagedState = raw.`EPOLeafNode.ManagedState`,
      EPOLeafNode_NodeName = raw.`EPOLeafNode.NodeName`,
      EPOComputerProperties_Description = raw.`EPOComputerProperties.Description`,
      EPOEvents_TargetMAC = raw.`EPOEvents.TargetMAC`,
      EPOEvents_ThreatCategory = raw.`EPOEvents.ThreatCategory`,
      EPOEvents_TargetUserName = raw.`EPOEvents.TargetUserName`,
      EPOEvents_SourceHostName = raw.`EPOEvents.SourceHostName`,
      EPOEvents_TargetIPV4 = raw.`EPOEvents.TargetIPV4`,
      EPOEvents_AnalyzerIPV4 = raw.`EPOEvents.AnalyzerIPV4`,
      EPOEvents_AnalyzerIPV6 = raw.`EPOEvents.AnalyzerIPV6`,
      EPOComputerProperties_SysvolTotalSpace = raw.`EPOComputerProperties.SysvolTotalSpace`,
      EPOEvents_AnalyzerDetectionMethod = raw.`EPOEvents.AnalyzerDetectionMethod`,
      EPOLeafNode_AgentGUID = raw.`EPOLeafNode.AgentGUID`,
      EPOEvents_ServerID = raw.`EPOEvents.ServerID`,
      EPOEvents_AnalyzerMAC = raw.`EPOEvents.AnalyzerMAC`,
      EPOComputerProperties_OSBitMode = raw.`EPOComputerProperties.OSBitMode`,
      EPOLeafNode_AgentVersion = raw.`EPOLeafNode.AgentVersion`,
      EPOComputerProperties_UserProperty1 = raw.`EPOComputerProperties.UserProperty1`,
      EPOComputerProperties_UserProperty3 = raw.`EPOComputerProperties.UserProperty3`,
      EPOComputerProperties_IsPortable = raw.`EPOComputerProperties.IsPortable`,
      EPOComputerProperties_FreeDiskSpace = raw.`EPOComputerProperties.FreeDiskSpace`,
      EPOEvents_SourceIPV6 = raw.`EPOEvents.SourceIPV6`,
      EPOEvents_SourceProcessName = raw.`EPOEvents.SourceProcessName`,
      EPOLeafNode_Tags = raw.`EPOLeafNode.Tags`,
      EPOEvents_ThreatActionTaken = raw.`EPOEvents.ThreatActionTaken`,
      EPOComputerProperties_CPUSpeed = raw.`EPOComputerProperties.CPUSpeed`,
      EPOComputerProperties_ComputerName = raw.`EPOComputerProperties.ComputerName`,
      EPOEvents_ThreatHandled = raw.`EPOEvents.ThreatHandled`,
      EPOComputerProperties_NetAddress = raw.`EPOComputerProperties.NetAddress`,
      EPOEvents_ThreatType = raw.`EPOEvents.ThreatType`,
      EPOEvents_TargetProtocol = raw.`EPOEvents.TargetProtocol`,
      EPOComputerProperties_IPV4x = raw.`EPOComputerProperties.IPV4x`,
      EPOComputerProperties_SysvolFreeSpace = raw.`EPOComputerProperties.SysvolFreeSpace`,
      EPOEvents_AnalyzerEngineVersion = raw.`EPOEvents.AnalyzerEngineVersion`,
      EPOComputerProperties_DomainName = raw.`EPOComputerProperties.DomainName`,
      EPOComputerProperties_UserName = raw.`EPOComputerProperties.UserName`,
      EPOComputerProperties_CPUType = raw.`EPOComputerProperties.CPUType`,
      EPOComputerProperties_TotalDiskSpace = raw.`EPOComputerProperties.TotalDiskSpace`,
      EPOEvents_ThreatEventID = raw.`EPOEvents.ThreatEventID`,
      EPOEvents_AnalyzerDATVersion = raw.`EPOEvents.AnalyzerDATVersion`,
      EPOComputerProperties_SubnetAddress = raw.`EPOComputerProperties.SubnetAddress`,
      EPOLeafNode_ExcludedTags = raw.`EPOLeafNode.ExcludedTags`,
      EPOEvents_DetectedUTC = stringToInstant(raw.`EPOEvents.DetectedUTC`),
      EPOComputerProperties_LastAgentHandler = raw.`EPOComputerProperties.LastAgentHandler`
    )
  }
}