package com.punchcyber.patternicity.common.datatype.hbss.record

import com.punchcyber.patternicity.common.datatype.json.record.{JsonRecord, JsonRecordRaw}
import java.time.Instant

case class HbssHipsEventRecordRaw(`EPOEvents.TargetPort`: Option[Int],
                                  `EPOEvents.TargetFileName`: Option[String],
                                  `EPOEvents.ThreatName`: Option[String],
                                  `EPOEvents.ThreatHandled`: Boolean,
                                  `HIP8.EventInfo.Direction`: Option[String],
                                  `EPOEvents.ThreatType`: Option[String],
                                  `EPOEvents.AnalyzerHostName`: Option[String],
                                  `EPOEvents.SourceProcessName`: Option[String],
                                  `EPOEvents.TargetProtocol`: Option[String],
                                  `EPOLeafNode.NodeName`: Option[String],
                                  `EPOEvents.SourceURL`: Option[String],
                                  `EPOEvents.ReceivedUTC`: String,
                                  `EPOEvents.TargetMAC`: Option[String],
                                  `HIP8.EventInfo.AppSigner`: Option[String],
                                  `HIP8.EventInfo.EventPolicyType`: Option[String],
                                  `EPOEvents.ThreatCategory`: Option[String],
                                  `EPOEvents.TargetUserName`: Option[String],
                                  `EPOEvents.SourceHostName`: Option[String],
                                  `EPOEvents.TargetIPV4`: Option[String],
                                  `EPOEvents.AnalyzerEngineVersion`: Option[String],
                                  `HIP8.EventInfo.SignatureName`: Option[String],
                                  `EPOEvents.AnalyzerIPV4`: Option[String],
                                  `EPOEvents.Analyzer`: Option[String],
                                  `EPOEvents.AnalyzerIPV6`: Option[String],
                                  `HIP8.EventInfo.EventUserName`: Option[String],
                                  `EPOEvents.AnalyzerDetectionMethod`: Option[String],
                                  `HIP8.EventInfo.Files`: Option[String],
                                  `EPOEvents.AnalyzerVersion`: Option[String],
                                  `EPOEvents.AnalyzerName`: Option[String],
                                  `HIP8.SigNameXlate.SignatureName`: Option[String],
                                  `EPOEvents.TargetProcessName`: Option[String],
                                  `EPOEvents.ServerID`: Option[String],
                                  `EPOBranchNode.NodeTextPath`: Option[String],
                                  `EPOEvents.AgentGUID`: Option[String],
                                  `EPOEvents.AnalyzerMAC`: Option[String],
                                  `EPOEvents.SourceMAC`: Option[String],
                                  `EPOEvents.ThreatEventID`: Int,
                                  `EPOEvents.TargetHostName`: Option[String],
                                  `EPOEvents.TargetIPV6`: Option[String],
                                  `EPOEvents.ThreatSeverity`: Int,
                                  `HIP8.EventInfo.Hidden`: Option[String],
                                  `ERP.View.HIP8.IPSEventParameter.ParameterValue`: Option[String],
                                  `EPOEvents.AnalyzerDATVersion`: Option[String],
                                  `HIP8.EventInfo.AppHash`: Option[String],
                                  `EPOEvents.SourceUserName`: Option[String],
                                  `ERP.View.HIP8.IPSEventParameter.ParameterName`: Option[String],
                                  `EPOEvents.SourceIPV6`: Option[String],
                                  `EPOEvents.SourceIPV4`: Option[String],
                                  `HIP8.EventInfo.DestinationFile`: Option[String],
                                  `ERP.View.HIP8.IPSEventParameter.EventID`: Long,
                                  `HIP8.EventInfo.AppDesc`: Option[String],
                                  `EPOEvents.ThreatActionTaken`: Option[String],
                                  `EPOEvents.DetectedUTC`: String) extends JsonRecordRaw

case class HbssHipsEventRecord(EPOEvents_TargetPort: Option[Int],
                               EPOEvents_TargetFileName: Option[String],
                               EPOEvents_ThreatName: Option[String],
                               EPOEvents_ThreatHandled: Boolean,
                               HIP8_EventInfo_Direction: Option[String],
                               EPOEvents_ThreatType: Option[String],
                               EPOEvents_AnalyzerHostName: Option[String],
                               EPOEvents_SourceProcessName: Option[String],
                               EPOEvents_TargetProtocol: Option[String],
                               EPOLeafNode_NodeName: Option[String],
                               EPOEvents_SourceURL: Option[String],
                               EPOEvents_ReceivedUTC: Instant,
                               EPOEvents_TargetMAC: Option[String],
                               HIP8_EventInfo_AppSigner: Option[String],
                               HIP8_EventInfo_EventPolicyType: Option[String],
                               EPOEvents_ThreatCategory: Option[String],
                               EPOEvents_TargetUserName: Option[String],
                               EPOEvents_SourceHostName: Option[String],
                               EPOEvents_TargetIPV4: Option[String],
                               EPOEvents_AnalyzerEngineVersion: Option[String],
                               HIP8_EventInfo_SignatureName: Option[String],
                               EPOEvents_AnalyzerIPV4: Option[String],
                               EPOEvents_Analyzer: Option[String],
                               EPOEvents_AnalyzerIPV6: Option[String],
                               HIP8_EventInfo_EventUserName: Option[String],
                               EPOEvents_AnalyzerDetectionMethod: Option[String],
                               HIP8_EventInfo_Files: Option[String],
                               EPOEvents_AnalyzerVersion: Option[String],
                               EPOEvents_AnalyzerName: Option[String],
                               HIP8_SigNameXlate_SignatureName: Option[String],
                               EPOEvents_TargetProcessName: Option[String],
                               EPOEvents_ServerID: Option[String],
                               EPOBranchNode_NodeTextPath: Option[String],
                               EPOEvents_AgentGUID: Option[String],
                               EPOEvents_AnalyzerMAC: Option[String],
                               EPOEvents_SourceMAC: Option[String],
                               EPOEvents_ThreatEventID: Int,
                               EPOEvents_TargetHostName: Option[String],
                               EPOEvents_TargetIPV6: Option[String],
                               EPOEvents_ThreatSeverity: Int,
                               HIP8_EventInfo_Hidden: Option[String],
                               ERP_View_HIP8_IPSEventParameter_ParameterValue: Option[String],
                               EPOEvents_AnalyzerDATVersion: Option[String],
                               HIP8_EventInfo_AppHash: Option[String],
                               EPOEvents_SourceUserName: Option[String],
                               ERP_View_HIP8_IPSEventParameter_ParameterName: Option[String],
                               EPOEvents_SourceIPV6: Option[String],
                               EPOEvents_SourceIPV4: Option[String],
                               HIP8_EventInfo_DestinationFile: Option[String],
                               ERP_View_HIP8_IPSEventParameter_EventID: Long,
                               HIP8_EventInfo_AppDesc: Option[String],
                               EPOEvents_ThreatActionTaken: Option[String],
                               EPOEvents_DetectedUTC: Instant) extends JsonRecord

object HbssHipsEventRecord extends JsonRecord {
  def apply(raw: HbssHipsEventRecordRaw): HbssHipsEventRecord = {
    HbssHipsEventRecord(EPOEvents_TargetPort = raw.`EPOEvents.TargetPort`,
      EPOEvents_TargetFileName = raw.`EPOEvents.TargetFileName`,
      EPOEvents_ThreatName = raw.`EPOEvents.ThreatName`,
      EPOEvents_ThreatHandled = raw.`EPOEvents.ThreatHandled`,
      HIP8_EventInfo_Direction = raw.`HIP8.EventInfo.Direction`,
      EPOEvents_ThreatType = raw.`EPOEvents.ThreatType`,
      EPOEvents_AnalyzerHostName = raw.`EPOEvents.AnalyzerHostName`,
      EPOEvents_SourceProcessName = raw.`EPOEvents.SourceProcessName`,
      EPOEvents_TargetProtocol = raw.`EPOEvents.TargetProtocol`,
      EPOLeafNode_NodeName = raw.`EPOLeafNode.NodeName`,
      EPOEvents_SourceURL = raw.`EPOEvents.SourceURL`,
      EPOEvents_ReceivedUTC = stringToInstant(raw.`EPOEvents.ReceivedUTC`),
      EPOEvents_TargetMAC = raw.`EPOEvents.TargetMAC`,
      HIP8_EventInfo_AppSigner = raw.`HIP8.EventInfo.AppSigner`,
      HIP8_EventInfo_EventPolicyType = raw.`HIP8.EventInfo.EventPolicyType`,
      EPOEvents_ThreatCategory = raw.`EPOEvents.ThreatCategory`,
      EPOEvents_TargetUserName = raw.`EPOEvents.TargetUserName`,
      EPOEvents_SourceHostName = raw.`EPOEvents.SourceHostName`,
      EPOEvents_TargetIPV4 = raw.`EPOEvents.TargetIPV4`,
      EPOEvents_AnalyzerEngineVersion = raw.`EPOEvents.AnalyzerEngineVersion`,
      HIP8_EventInfo_SignatureName = raw.`HIP8.EventInfo.SignatureName`,
      EPOEvents_AnalyzerIPV4 = raw.`EPOEvents.AnalyzerIPV4`,
      EPOEvents_Analyzer = raw.`EPOEvents.Analyzer`,
      EPOEvents_AnalyzerIPV6 = raw.`EPOEvents.AnalyzerIPV6`,
      HIP8_EventInfo_EventUserName = raw.`HIP8.EventInfo.EventUserName`,
      EPOEvents_AnalyzerDetectionMethod = raw.`EPOEvents.AnalyzerDetectionMethod`,
      HIP8_EventInfo_Files = raw.`HIP8.EventInfo.Files`,
      EPOEvents_AnalyzerVersion = raw.`EPOEvents.AnalyzerVersion`,
      EPOEvents_AnalyzerName = raw.`EPOEvents.AnalyzerName`,
      HIP8_SigNameXlate_SignatureName = raw.`HIP8.SigNameXlate.SignatureName`,
      EPOEvents_TargetProcessName = raw.`EPOEvents.TargetProcessName`,
      EPOEvents_ServerID = raw.`EPOEvents.ServerID`,
      EPOBranchNode_NodeTextPath = raw.`EPOBranchNode.NodeTextPath`,
      EPOEvents_AgentGUID = raw.`EPOEvents.AgentGUID`,
      EPOEvents_AnalyzerMAC = raw.`EPOEvents.AnalyzerMAC`,
      EPOEvents_SourceMAC = raw.`EPOEvents.SourceMAC`,
      EPOEvents_ThreatEventID = raw.`EPOEvents.ThreatEventID`,
      EPOEvents_TargetHostName = raw.`EPOEvents.TargetHostName`,
      EPOEvents_TargetIPV6 = raw.`EPOEvents.TargetIPV6`,
      EPOEvents_ThreatSeverity = raw.`EPOEvents.ThreatSeverity`,
      HIP8_EventInfo_Hidden = raw.`HIP8.EventInfo.Hidden`,
      ERP_View_HIP8_IPSEventParameter_ParameterValue = raw.`ERP.View.HIP8.IPSEventParameter.ParameterValue`,
      EPOEvents_AnalyzerDATVersion = raw.`EPOEvents.AnalyzerDATVersion`,
      HIP8_EventInfo_AppHash = raw.`HIP8.EventInfo.AppHash`,
      EPOEvents_SourceUserName = raw.`EPOEvents.SourceUserName`,
      ERP_View_HIP8_IPSEventParameter_ParameterName = raw.`ERP.View.HIP8.IPSEventParameter.ParameterName`,
      EPOEvents_SourceIPV6 = raw.`EPOEvents.SourceIPV6`,
      EPOEvents_SourceIPV4 = raw.`EPOEvents.SourceIPV4`,
      HIP8_EventInfo_DestinationFile = raw.`HIP8.EventInfo.DestinationFile`,
      ERP_View_HIP8_IPSEventParameter_EventID = raw.`ERP.View.HIP8.IPSEventParameter.EventID`,
      HIP8_EventInfo_AppDesc = raw.`HIP8.EventInfo.AppDesc`,
      EPOEvents_ThreatActionTaken = raw.`EPOEvents.ThreatActionTaken`,
      EPOEvents_DetectedUTC = stringToInstant(raw.`EPOEvents.DetectedUTC`))
  }
}
